version: "3.8"
services:
  swagger-ui:
    image: docker-push.tamin.ir:8182/tamin/apps/swagger-ui:1.0
    container_name: swagger-ui
    ports:
      - "8022:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.yaml
    volumes:
      - ./swagger.yaml:/docs/swagger.yaml

  swagger-editor:
    image: docker-push.tamin.ir:8182/tamin/apps/swagger-editor:1.0
    container_name: swagger-editor
    ports:
      - "8033:8080"
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
